// Static data for the onboarding form selects. Plain module, safe to import
// client-side. The same list backs both the country select and the phone
// dial-code select so there is one source of truth; the API route validates
// submitted values against it.

export type Country = { code: string; name: string; dial: string };

export const COUNTRIES: Country[] = [
  { code: "AL", name: "Albania", dial: "355" },
  { code: "DZ", name: "Algeria", dial: "213" },
  { code: "AD", name: "Andorra", dial: "376" },
  { code: "AR", name: "Argentina", dial: "54" },
  { code: "AM", name: "Armenia", dial: "374" },
  { code: "AU", name: "Australia", dial: "61" },
  { code: "AT", name: "Austria", dial: "43" },
  { code: "AZ", name: "Azerbaijan", dial: "994" },
  { code: "BH", name: "Bahrain", dial: "973" },
  { code: "BD", name: "Bangladesh", dial: "880" },
  { code: "BY", name: "Belarus", dial: "375" },
  { code: "BE", name: "Belgium", dial: "32" },
  { code: "BO", name: "Bolivia", dial: "591" },
  { code: "BA", name: "Bosnia and Herzegovina", dial: "387" },
  { code: "BR", name: "Brazil", dial: "55" },
  { code: "BG", name: "Bulgaria", dial: "359" },
  { code: "KH", name: "Cambodia", dial: "855" },
  { code: "CM", name: "Cameroon", dial: "237" },
  { code: "CA", name: "Canada", dial: "1" },
  { code: "CL", name: "Chile", dial: "56" },
  { code: "CN", name: "China", dial: "86" },
  { code: "CO", name: "Colombia", dial: "57" },
  { code: "CR", name: "Costa Rica", dial: "506" },
  { code: "HR", name: "Croatia", dial: "385" },
  { code: "CY", name: "Cyprus", dial: "357" },
  { code: "CZ", name: "Czechia", dial: "420" },
  { code: "DK", name: "Denmark", dial: "45" },
  { code: "DO", name: "Dominican Republic", dial: "1" },
  { code: "EC", name: "Ecuador", dial: "593" },
  { code: "EG", name: "Egypt", dial: "20" },
  { code: "SV", name: "El Salvador", dial: "503" },
  { code: "EE", name: "Estonia", dial: "372" },
  { code: "ET", name: "Ethiopia", dial: "251" },
  { code: "FI", name: "Finland", dial: "358" },
  { code: "FR", name: "France", dial: "33" },
  { code: "GE", name: "Georgia", dial: "995" },
  { code: "DE", name: "Germany", dial: "49" },
  { code: "GH", name: "Ghana", dial: "233" },
  { code: "GR", name: "Greece", dial: "30" },
  { code: "GT", name: "Guatemala", dial: "502" },
  { code: "HN", name: "Honduras", dial: "504" },
  { code: "HK", name: "Hong Kong", dial: "852" },
  { code: "HU", name: "Hungary", dial: "36" },
  { code: "IS", name: "Iceland", dial: "354" },
  { code: "IN", name: "India", dial: "91" },
  { code: "ID", name: "Indonesia", dial: "62" },
  { code: "IQ", name: "Iraq", dial: "964" },
  { code: "IE", name: "Ireland", dial: "353" },
  { code: "IL", name: "Israel", dial: "972" },
  { code: "IT", name: "Italy", dial: "39" },
  { code: "JP", name: "Japan", dial: "81" },
  { code: "JO", name: "Jordan", dial: "962" },
  { code: "KZ", name: "Kazakhstan", dial: "7" },
  { code: "KE", name: "Kenya", dial: "254" },
  { code: "XK", name: "Kosovo", dial: "383" },
  { code: "KW", name: "Kuwait", dial: "965" },
  { code: "LV", name: "Latvia", dial: "371" },
  { code: "LB", name: "Lebanon", dial: "961" },
  { code: "LI", name: "Liechtenstein", dial: "423" },
  { code: "LT", name: "Lithuania", dial: "370" },
  { code: "LU", name: "Luxembourg", dial: "352" },
  { code: "MY", name: "Malaysia", dial: "60" },
  { code: "MT", name: "Malta", dial: "356" },
  { code: "MX", name: "Mexico", dial: "52" },
  { code: "MD", name: "Moldova", dial: "373" },
  { code: "MC", name: "Monaco", dial: "377" },
  { code: "MN", name: "Mongolia", dial: "976" },
  { code: "ME", name: "Montenegro", dial: "382" },
  { code: "MA", name: "Morocco", dial: "212" },
  { code: "NP", name: "Nepal", dial: "977" },
  { code: "NL", name: "Netherlands", dial: "31" },
  { code: "NZ", name: "New Zealand", dial: "64" },
  { code: "NG", name: "Nigeria", dial: "234" },
  { code: "MK", name: "North Macedonia", dial: "389" },
  { code: "NO", name: "Norway", dial: "47" },
  { code: "OM", name: "Oman", dial: "968" },
  { code: "PK", name: "Pakistan", dial: "92" },
  { code: "PA", name: "Panama", dial: "507" },
  { code: "PY", name: "Paraguay", dial: "595" },
  { code: "PE", name: "Peru", dial: "51" },
  { code: "PH", name: "Philippines", dial: "63" },
  { code: "PL", name: "Poland", dial: "48" },
  { code: "PT", name: "Portugal", dial: "351" },
  { code: "QA", name: "Qatar", dial: "974" },
  { code: "RO", name: "Romania", dial: "40" },
  { code: "RU", name: "Russia", dial: "7" },
  { code: "SM", name: "San Marino", dial: "378" },
  { code: "SA", name: "Saudi Arabia", dial: "966" },
  { code: "SN", name: "Senegal", dial: "221" },
  { code: "RS", name: "Serbia", dial: "381" },
  { code: "SG", name: "Singapore", dial: "65" },
  { code: "SK", name: "Slovakia", dial: "421" },
  { code: "SI", name: "Slovenia", dial: "386" },
  { code: "ZA", name: "South Africa", dial: "27" },
  { code: "KR", name: "South Korea", dial: "82" },
  { code: "ES", name: "Spain", dial: "34" },
  { code: "LK", name: "Sri Lanka", dial: "94" },
  { code: "SE", name: "Sweden", dial: "46" },
  { code: "CH", name: "Switzerland", dial: "41" },
  { code: "TW", name: "Taiwan", dial: "886" },
  { code: "TZ", name: "Tanzania", dial: "255" },
  { code: "TH", name: "Thailand", dial: "66" },
  { code: "TN", name: "Tunisia", dial: "216" },
  { code: "TR", name: "Turkey", dial: "90" },
  { code: "UA", name: "Ukraine", dial: "380" },
  { code: "AE", name: "United Arab Emirates", dial: "971" },
  { code: "GB", name: "United Kingdom", dial: "44" },
  { code: "US", name: "United States", dial: "1" },
  { code: "UY", name: "Uruguay", dial: "598" },
  { code: "UZ", name: "Uzbekistan", dial: "998" },
  { code: "VE", name: "Venezuela", dial: "58" },
  { code: "VN", name: "Vietnam", dial: "84" },
];

export type Currency = { code: string; label: string; flag: string };

export const CURRENCIES: Currency[] = [
  { code: "USD", label: "US Dollar ($)", flag: "US" },
  { code: "EUR", label: "Euro (€)", flag: "EU" },
  { code: "GBP", label: "British Pound (£)", flag: "GB" },
  { code: "SEK", label: "Swedish Krona (kr)", flag: "SE" },
  { code: "NOK", label: "Norwegian Krone (kr)", flag: "NO" },
  { code: "DKK", label: "Danish Krone (kr)", flag: "DK" },
  { code: "CHF", label: "Swiss Franc (CHF)", flag: "CH" },
  { code: "PLN", label: "Polish Zloty (zł)", flag: "PL" },
  { code: "CZK", label: "Czech Koruna (Kč)", flag: "CZ" },
  { code: "HUF", label: "Hungarian Forint (Ft)", flag: "HU" },
  { code: "RON", label: "Romanian Leu (lei)", flag: "RO" },
  { code: "BGN", label: "Bulgarian Lev (лв)", flag: "BG" },
  { code: "RSD", label: "Serbian Dinar (din)", flag: "RS" },
  { code: "BAM", label: "Bosnian Mark (KM)", flag: "BA" },
  { code: "CAD", label: "Canadian Dollar ($)", flag: "CA" },
  { code: "AUD", label: "Australian Dollar ($)", flag: "AU" },
];

/** "DE" → 🇩🇪 via regional-indicator codepoints; no emoji column needed. */
export function flagEmoji(code: string): string {
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map((c) => 0x1f1a5 + c.charCodeAt(0)),
  );
}

// Validation sets shared by the onboarding form, API, and admin editor.
export const COUNTRY_CODES = new Set(COUNTRIES.map((c) => c.code));
export const DIAL_CODES = new Set(COUNTRIES.map((c) => c.dial));
export const CURRENCY_CODES = new Set(CURRENCIES.map((c) => c.code));
